FROM apache/nifi

# WORKDIR /nifi-deploy

COPY flow_template.xml /opt/nifi/conf/templates
# COPY deploy_nifi.sh deploy_nifi.sh

# ENTRYPOINT ["/bin/bash", "deploy_nifi.sh"]
# ENV SINGLE_USER_CREDENTIALS_USERNAME=admin
# ENV SINGLE_USER_CREDENTIALS_PASSWORD=adminadminadmin
